name: build

on: ["push"]

jobs:
    test:
        name: Run test with coverage
        runs-on: ubuntu-latest
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.3
            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v2.5.2
            - name: test
              run: make test-coverage
            - name: upload coverage to codecov.io
              run: bash <(curl -s https://codecov.io/bash)
    linux32:
        name: Check build linux-386 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make vendor && make build-linux32
    linux64:
        name: Check build linux-amd64 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make vendor && make build-linux64
    win32:
        name: Check build win32 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make vendor && make build-win32
    win64:
        name: Check build win64 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make vendor && make build-win64
    macos:
        name: Check build macos binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make vendor && make build-mac
