name: build

on:
    push:
        branches:
            - "development"
            - "main"

jobs:
    test:
        name: Run test with coverage
        runs-on: ubuntu-latest
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 1
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v3
            - name: test
              run: make test
    linux32:
        name: Check build linux-386 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make tidy && make build-linux32
    linux64:
        name: Check build linux-amd64 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make tidy && make build-linux64
    win32:
        name: Check build win32 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make tidy && make build-win32
    win64:
        name: Check build win64 binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make tidy && make build-win64
    macos:
        name: Check build macos binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: Check build
              run: make tidy && make build-mac
