name: release

on:
    push:
        tags:
            - "*"

jobs:
    linux32:
        name: build linux-386 binary
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: build
              run: make tidy && make build-linux32 VERSION=$GITHUB_REF_NAME
            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./bin/swisstools
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
    linux64:
        name: build linux-amd64 binary
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: build
              run: make tidy && make build-linux64 VERSION=$GITHUB_REF_NAME
            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./bin/swisstools-amd64
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
    win32:
        name: build win32 binary
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: build
              run: make tidy && make build-win32 VERSION=$GITHUB_REF_NAME
            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./bin/swisstools-i386.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
    win64:
        name: build win64 binary
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: build
              run: make tidy && make build-win64 VERSION=$GITHUB_REF_NAME
            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./bin/swisstools-x64.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
    macos:
        name: build macos binary
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20.3
            - name: build
              run: make tidy && make build-mac VERSION=$GITHUB_REF_NAME
            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./bin/swisstools-darwin-amd64
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
