name: release

on:
  push:
    tags:
      - "*"

env:
  GO_VERSION: '1.21.4'

jobs:
  linux32:
    name: build linux-386 binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make tidy && make build-linux32 VERSION=$GITHUB_REF_NAME
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/swisstools
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  linux64:
    name: build linux-amd64 binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make tidy && make build-linux64 VERSION=$GITHUB_REF_NAME
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/swisstools-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  win32:
    name: build win32 binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make tidy && make build-win32 VERSION=$GITHUB_REF_NAME
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/swisstools-i386.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  win64:
    name: build win64 binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make tidy && make build-win64 VERSION=$GITHUB_REF_NAME
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/swisstools-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  macos-amd:
    name: build macos binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make tidy && make build-mac-amd VERSION=$GITHUB_REF_NAME
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/swisstools-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  macos-arm:
    name: build macos binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make tidy && make build-mac-arm VERSION=$GITHUB_REF_NAME
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/swisstools-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
